#spring.application.name=Service-Registry
spring:
  application:
    name: Service-Registry
server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

