spring:
  application:
    name: User-Micro-Service
server:
  port: 8083
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerceuser
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8082/eureka/

